### ISSUE TITLE
Many google-web-components don't resolve to a valid spdx license identifier

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/beta#232]
We can't show these elements on the site until our system understands their license correctly:

* [x] firebase-element
* [x] google-analytics
* [x] google-apis
* [x] google-calendar
* [x] google-castable-video
* [x] google-chart
* [x] google-hangout-button
* [x] google-map
* [x] google-sheets
* [x] google-signin
* [x] google-streetview-pano
* [x] google-url-shortener
* [x] google-web-components

eg. google-web-components includes `"license": "BSD",` in its `bower.json` but that isn't a valid [SDPX Identifier](https://spdx.org/licenses/).

google-feeds comes up as BSD-2-Clause based on the `LICENSE` file, but its `bower.json` says Apache-2.

@addyosmani @ebidel

**Comment by ebidel** [comment]
@rictic @azakus is there a bower.json update script we can run to change all of the licenses to https://github.com/PolymerElements/iron-list/blob/master/bower.json#L20?

**Comment by rictic** [comment]
I don't think that there's an existing tedium pass to do this. Wouldn't be hard to add one except that the script would need to be able to tell that a repo should have that as its license field.

**Comment by tjsavage** [comment]
I'll go through and update all these right now.

**Comment by tjsavage** [comment]
Fixed up all these licenses - LMK if there are still ones that are broken.

**Comment by rictic** [comment]
Awesome, thanks Taylor!

**Comment by dstockwell** [comment]
Perfect, they're all live now.
