### ISSUE TITLE
Several elements don't generate documentation

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/beta#238]
* [x] PolymerElements/paper-radio-group
 * This has broken dependencies -- some actual dependencies (like paper-radio-button) are listed as devDependencies.
* [x] PolymerElements/paper-badge
* [x] PolymerElements/iron-test-helpers
* [x] PolymerElements/iron-iconset

**Comment by andymutton** [comment]
Iron test helpers has no elements and no documentation for them AFAIK.
https://elements.polymer-project.org/elements/iron-test-helpers

**Comment by andymutton** [comment]
Pull requests have been made for paper-radio-group and paper-badge.

iron-iconset is weird. bower says it can't find the main html file, despite the fact that it's clearly listed in the bower.json and is definitely in the file system. I'll keep investigating.

analysis/processNextTask {"owner":"PolymerElements","repo":"iron-iconset","version":"v1.0.4"}
bower/prune
bower/prune/success
bower/install PolymerElements/iron-iconset#v1.0.4
bower/install/success PolymerElements/iron-iconset#v1.0.4
bower/install Couldn't find main.html after installing PolymerElements/iron-iconset#v1.0.4 { endpoint: 
   { name: 'iron-iconset',
     source: 'PolymerElements/iron-iconset',
     target: 'v1.0.4' },
  canonicalDir: '/usr/local/google/home/andymutton/src/custom-elementsv2/analysis/bower_components/iron-iconset',
  pkgMeta: 
   { name: 'iron-iconset',
     version: '1.0.4',
     license: 'http://polymer.github.io/LICENSE.txt',
     description: 'Represents a set of icons',
     authors: [ 'The Polymer Authors' ],
     keywords: [ 'web-components', 'polymer', 'icon' ],
     repository: 
      { type: 'git',
        url: 'git://github.com/PolymerElements/iron-iconset.git' },
     private: true,
     dependencies: 
      { 'iron-meta': 'PolymerElements/iron-meta#^1.0.0',
        polymer: 'Polymer/polymer#^1.0.0' },
     devDependencies: 
      { 'iron-component-page': 'polymerelements/iron-component-page#^1.0.0',
        'iron-icon': 'polymerelements/iron-icon#^1.0.0',
        'promise-polyfill': 'polymerlabs/promise-polyfill#^1.0.0',
        'test-fixture': 'PolymerElements/test-fixture#^1.0.0',
        'web-component-tester': '*',
        webcomponentsjs: 'webcomponents/webcomponentsjs#^0.7.0' },
     homepage: 'https://github.com/PolymerElements/iron-iconset',
     _release: '1.0.4',
     _resolution: 
      { type: 'version',
        tag: 'v1.0.4',
        commit: '97898a86053923b2787bac86c6e8133bb3f34566' },
     _source: 'git://github.com/PolymerElements/iron-iconset.git',
     _target: '^1.0.4' },
  dependencies: 
   { 'iron-meta': 
      { endpoint: [Object],
        canonicalDir: '/usr/local/google/home/andymutton/src/custom-elementsv2/analysis/bower_components/iron-meta',
        pkgMeta: [Object],
        dependencies: [Object],
        nrDependants: 1 },
     polymer: 
      { endpoint: [Object],
        canonicalDir: '/usr/local/google/home/andymutton/src/custom-elementsv2/analysis/bower_components/polymer',
        pkgMeta: [Object],
        dependencies: [Object],
        nrDependants: 2 } },
  nrDependants: 0 }
hydrolysis/analyze []
bower/findDependencies PolymerElements/iron-iconset#v1.0.4

**Comment by andymutton** [comment]
iron-iconset's issue is that that 1.0.4 bower.json doesn't contain a "main" property. We need a new version.

**Comment by andymutton** [comment]
The three that can be fixed should be good now.
