### ISSUE TITLE
Client: Rewrite iron-component-page

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/beta#244]

**Comment by samuelli** [comment]
@andymutton did you want to take this up? Making our own version of iron-component-page and making it match our styling

**Comment by samuelli** [comment]
@andymutton: Not sure if this is an updated iron-doc-viewer or what, but it looks decent.

https://ebidel.github.io/geo-location/components/geo-location/

**Comment by samuelli** [comment]
Closing as mostly done.
