### ISSUE TITLE
cmd+click on a demo should open up in a new tab without the modal

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/beta#294]

**Comment by dstockwell** [comment]
I'm not sure, I think this would be quite surprising behavior. The target of the link appears in the browser status bar, it's misleading for 'open as new tab' to go somewhere else.

**Comment by tjsavage** [comment]
Fair. I think the largest issue is there's no way to navigate directly to just a demo page - I would almost expect that's what a link like https://custom-elements-staging.appspot.com/element/PolymerElements/paper-tabs/v1.6.2/demo/demo/index.html would lead to (rather than a modal on top).

I don't think we need to figure this out right now though. Closing for now.
