### ISSUE TITLE
Element API goes to unexpected place

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/beta#342]
I still think we should rename the top entry to something like Overview and always use the element/behavior names in the other entries.

![screenshot 2016-10-04 at 22 16 01](https://cloud.githubusercontent.com/assets/539597/19072302/2b949c9c-8a80-11e6-98b1-c6c786a87988.png)

**Comment by samuelli** [comment]
This has been updated to show "Overview" for readme.md if the same name appears. "Element API" is removed, always shows name with API on right.
