### ISSUE TITLE
Architecture for community content

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/beta#350]
## Background

The existing webcomponents.org site is generated using DocPad. Entities like articles, polyfills and browser compatibility are authored in a markdown-like format, eg. [polyfills](https://github.com/webcomponents/webcomponents.github.io/blob/site/src/documents/polyfills/index.html.md)
## Beta

In beta, we expect most community contributions to be in the form of elements, collections, articles, podcasts and presentations. Static content (articles, podcasts, presentations) will likely be presented in a single "community contributions" section @tjsavage @samuelli.
### Community content

For this content we should keep the contribution process trivial. Authors should write and submit markdown files with basic metadata -- we shouldn't require these contributions to involve checking out and running the client.

Rather than having a manual generation or commit hook step, we'll move to having the beta backend poll a GitHub repository for changes  (probably https://github.com/webcomponents/community). This will be similar to how it polls GitHub for updates to custom elements and collections. We won't run DocPad, but instead just extract metadata and use the GitHub API to process the article markdown. We'll only support basic github-flavored markdown with metadata sections at the top.

We should be able to import all of the existing content and continue to split out a separate excerpt and article body. For the existing metadata in the format:

```

---
title: Creating a Polymer Chat App with Material Design
authors: [tomomi_imura]
date: 2015-02-14
original_date: 2015-01-15
link: http://www.pubnub.com/blog/creating-a-polymer-chat-app-with-material-design/
category: articles
layout: single
tags: ['Polymer']

---
```
1. The `layout` tags won't be required.
2. We can import the existing authors.js file, but we should move to referencing authors as users on GitHub.
### Curated content

For content like "specs" or "libraries" we will either move to maintaining a single article entitiy for each, or hand-curate them as part of the client.
### Validation

We'll set up travis to validate content and metadata are well formed before pull requests are merged.

**Comment by Nevraeka** [comment]
@tjsavage Many content authors are  not on github. How do we include authors who do not have a github account?

**Comment by tjsavage** [comment]
This overall makes sense to me. Having like a `content/` folder in community might make it really easy to submit something.

@Nevraeka good point. perhaps we can keep an `authors` file in `content/` around for those not on github.

**Comment by Nevraeka** [comment]
@tjsavage it's a good short term solution since the authors are not in the thousands yet. Longer term we might want a more automated system that is agnostic to where the profile comes from

**Comment by samuelli** [comment]
Community content now hosted on https://github.com/webcomponents/community

Sample article: https://beta.webcomponents.org/community/articles/polymer-in-production
