### ISSUE TITLE
Accepted open source license

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/beta#400]
About the "All licenses recognised by the [Open Source Initative](https://opensource.org/licenses/alphabetical) are accepted".

What happens if I have a recognised license (MIT), but in the `bower.json:license` property I have an URL? Like the PolymerElements.

Thanks in advance!

**Comment by dstockwell** [comment]
We prefer GitHub license detection (https://github.com/blog/2252-license-now-displayed-on-repository-overview) over bower.json. So if the repo includes a LICENSE or COPYING file it's probably already OK.

We fall back to bower.json only when GitHub can't identify the license. In the case of a widely used URL like in PolymerElements we have the option to [manually validate and whitelist](https://github.com/webcomponents/beta/blob/master/src/licenses.py#L5), but this won't scale and I think we would prefer to do this only for widely referenced licenses. We have asked for Polymer to consider a different approach to avoid the whitelist.

**Comment by abdonrd** [comment]
@dstockwell thanks for the explication!
