### ISSUE TITLE
`npm run` commands for simpler installation

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/beta#402]
Could we add `npm run` commands to more easily install & run the client? Like `npm run client`?

Also need to add a note in the README for the client to run `bower install`

**Comment by andymutton** [comment]
npm run client does the following:

cd client && bower install && dev_appserver.py client.yaml

which should be fine, assuming that bower and appengine are installed

**Comment by samuelli** [comment]
Can you add it to readme?
