### ISSUE TITLE
Searching for "check" has no results but "checkbox" does

### ISSUE THREAD

**Issue by santokii** [webcomponents/beta#416]
Because a lot of titles have phrases with no sentence breaks, maybe add the ability to search for words within phrases or titles that may not be separated out? Also, on the reverse side some words like datepicker may be searched as 1 word as apposed as 2.

**Comment by andymutton** [comment]
'check' now returns what it should (as does 'che', 'chec', 'checkb' ... ). 'box' does not, but it's not clear that introducing word-splitting/dictionary matching is a sensible option here.

Title and camel case splits are also taken care of (eg. 'che', chec', 'box', 'but', 'butt', 'butto' will match CheckBoxButton)

Prefix based indexing and matching should solve most search issues, so closing this pending additional need.
