### ISSUE TITLE
A11y: tabbing through page gets stuck in the editor

### ISSUE THREAD

**Issue by ebidel** [webcomponents/beta#422]
Eventually, I get stuck in the code editor and can't tab out.

![screen shot 2016-10-10 at 11 39 37 am](https://cloud.githubusercontent.com/assets/238208/19247068/40c1f404-8ede-11e6-83f7-0245efdf7179.png)

**Comment by samuelli** [comment]
Not sure how if its really possible to fix this one. Same issue on all the pages I've found with CodeMirror.

It doesn't break voice over on OS X.

**Comment by samuelli** [comment]
This isn't an issue anymore for any first time users. (An overlay is shown on editors).

AFAIK, this doesn't break a11y readers, so I'm going to close it without a reasonable fix. Generic problem with most editor sites, eg. jsfiddle.net
