### ISSUE TITLE
Search: no results should have autocomplete banner saying so

### ISSUE THREAD

**Issue by ebidel** [webcomponents/beta#423]
When searching for something that does not have results, the autocomplete banner does not pop up. Nothing happens and pressing enter doesn't do anything :(

![screen shot 2016-10-10 at 11 40 22 am](https://cloud.githubusercontent.com/assets/238208/19247109/70f4a112-8ede-11e6-8b4c-044923d0a71f.png)

**Comment by samuelli** [comment]
This should be fixed soon, next push has a loading bar which will at least stop. We'll then have an actual search results page.
