### ISSUE TITLE
Search box should have a max height

### ISSUE THREAD

**Issue by samuelli** [webcomponents/beta#440]
[Origin page](https://beta.webcomponents.org/)

**Comment by Nevraeka** [comment]
on mobile with `.catalog-search-box-0 #search-input.catalog-search-box` selector having `max-height` set to `100px` works well. Check it out and I can push changes if that works

**Comment by samuelli** [comment]
Didn't work for me. The issue is mobile search, you can scroll the results which is a little strange

**Comment by Nevraeka** [comment]
i see . :(

**Comment by samuelli** [comment]
Closing as too low-pri. Functional but not ideal on mobile.
