### ISSUE TITLE
Last updated is incorrect

### ISSUE THREAD

**Issue by samuelli** [webcomponents/beta#443]
[Origin page](https://beta.webcomponents.org/element/PolymerElements/platinum-bluetooth)

https://github.com/PolymerElements/platinum-bluetooth/commits/master last updated 11th October. Currently says last updated 2 months ago.

**Comment by dstockwell** [comment]
GitHub bug? I just accessed https://api.github.com/repos/PolymerElements/platinum-bluetooth/stats/participation and got

```{json}
{
  "all": [
    0,
    0,
    4,
    2,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    3,
    1,
    15,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    0,
    0,
    2,
    0,
    0,
    5,
    1,
    1,
    0,
    0,
    0,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    3,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ],
```

**Comment by samuelli** [comment]
It's correct now, looks like there's a lag for the GitHub API.
