### ISSUE TITLE
Demos that assume index.html don't work

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/beta#444]
eg. https://beta.webcomponents.org/element/PolymerElements/platinum-bluetooth/v2.1.2/demo/demo/

**Comment by beaufortfrancois** [comment]
And here's the JS console:

```js
cdn.rawgit.com/:16 GET https://cdn.rawgit.com/polymerelements/platinum-bluetooth/webcomponentsjs/webcomponents-lite.js 
cdn.rawgit.com/:18 GET https://cdn.rawgit.com/polymerelements/platinum-bluetooth/iron-demo-helpers/demo-pages-shared-styles.html 404 ()
cdn.rawgit.com/:19 GET https://cdn.rawgit.com/polymerelements/platinum-bluetooth/marked-element/marked-element.html 404 ()
cdn.rawgit.com/:20 GET https://cdn.rawgit.com/polymerelements/platinum-bluetooth/paper-button/paper-button.html 404 ()
cdn.rawgit.com/:21 GET https://cdn.rawgit.com/polymerelements/platinum-bluetooth/paper-item/paper-item.html 404 ()
cdn.rawgit.com/:22 GET https://cdn.rawgit.com/polymerelements/platinum-bluetooth/paper-material/paper-material.html 404 ()
cdn.rawgit.com/:23 GET https://cdn.rawgit.com/polymerelements/platinum-bluetooth/paper-progress/paper-progress.html 404 ()
cdn.rawgit.com/:242 GET https://cdn.rawgit.com/polymerelements/platinum-bluetooth/polymer/polymer.html 404 ()
platinum-bluetooth-device.html:104 Uncaught ReferenceError: Polymer is not defined
    at platinum-bluetooth-device.html:104
    at platinum-bluetooth-device.html:263
(anonymous) @ platinum-bluetooth-device.html:104
(anonymous) @ platinum-bluetooth-device.html:263
platinum-bluetooth-service.html:68 Uncaught ReferenceError: Polymer is not defined
    at platinum-bluetooth-service.html:68
    at platinum-bluetooth-service.html:129
(anonymous) @ platinum-bluetooth-service.html:68
(anonymous) @ platinum-bluetooth-service.html:129
platinum-bluetooth-characteristic.html:199 Uncaught ReferenceError: Polymer is not defined
    at platinum-bluetooth-characteristic.html:199
    at platinum-bluetooth-characteristic.html:506
(anonymous) @ platinum-bluetooth-characteristic.html:199
(anonymous) @ platinum-bluetooth-characteristic.html:506

**Comment by beaufortfrancois** [comment]
https://beta.webcomponents.org/element/PolymerElements/platinum-bluetooth/v2.1.2/demo/demo/index.html works fine

**Comment by beaufortfrancois** [comment]
Please let me know when it's live so that I can check.
As of now, https://beta.webcomponents.org/element/PolymerElements/platinum-bluetooth/v2.1.2/demo/demo/ is still bogus ;(

**Comment by samuelli** [comment]
We haven't pushed the change yet.

You can see the fix on the staging site: https://custom-elements-staging.appspot.com/element/PolymerElements/platinum-bluetooth/v2.1.2/demo/demo/

**Comment by beaufortfrancois** [comment]
https://elements.polymer-project.org/elements/platinum-bluetooth?view=demo:demo/index.html&active=platinum-bluetooth-device works fine.
https://custom-elements-staging.appspot.com/element/PolymerElements/platinum-bluetooth/v2.1.2/demo/demo/ doesn't because the Web Bluetooth API is not allowed to be called from cross-origin iframe.

Do we have to use a separate domain for demos?

**Comment by dstockwell** [comment]
> Do we have to use a separate domain for Polymer demos?

Yes, unfortunately we can't host user content on the same domain.

**Comment by dstockwell** [comment]
@beaufortfrancois we could eventually support an option to not frame the demo. In the meantime could you detect this situation and display a link with a target to open the framed address in a new window?

**Comment by beaufortfrancois** [comment]
That would mean bumping the library version just for the sake of changing a demo that doesn't work in this version of the Polymer catalog but works fine on https://elements.polymer-project.org/elements/platinum-bluetooth?view=demo:demo/index.html&active=platinum-bluetooth-device.

That's a bummer. Are there any other workaround?
