### ISSUE TITLE
<emoji-rain> demo not raining

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/beta#448]
https://beta.webcomponents.org/element/notwaldorf/emoji-rain/v1.0.0/demo/index.html

It doesn't make it rain ;_;

**Comment by dstockwell** [comment]
I *think* it's because `index.html` uses unusual paths to reference dependencies:

`<link rel="import" href="bower_components/polymer/polymer.html">`
rather than
`<link rel="import" href="../polymer/polymer.html">`

We can possibly work around this on our end.

**Comment by dstockwell** [comment]
I couldn't actually figure out how to work around this. We end up loading polymer.html from two different locations. If I `301` redirect one to the other, they don't dedupe.

@notwaldorf is this repo just out of date? It has `bower_components` checked in, which is then referred to in `index.html`

**Comment by notwaldorf** [comment]
@dstockwell hmmm yes probably. it's before I knew how to write a script to correctly publish the demo and the element together. let me try to fix it.

**Comment by samuelli** [comment]
Closing as it seems like its not an issue on our end.
