### ISSUE TITLE
Absolute paths in the readme

### ISSUE THREAD

**Issue by blasten** [webcomponents/beta#450]
First of all, congrats to the team for the great work! Keep it up.

I just wanted to report that if I go to [PolymerElements/app-layout](https://beta.webcomponents.org/element/PolymerElements/app-layout), the links to the elements are broken.

The app-layout readme uses absolute paths to make them work on GitHub: https://github.com/PolymerElements/app-layout

Thanks!

[Origin page](https://beta.webcomponents.org/element/PolymerElements/app-layout)

**Comment by dstockwell** [comment]
Where should these links go? On GitHub they go to `.md` files that contain the same contents as the generated documentation.

Probably we should delete the `.md` files and link to the documentation directly.

**Comment by blasten** [comment]
@dstockwell I think, they could go to `https://beta.webcomponents.org/element/PolymerElements/app-layout/app-toolbar`  given that `https://beta.webcomponents.org/element/PolymerElements/app-layout` is the root. 

You can see that in the `README.md` we use absolute paths so that GitHub can transform the paths when I switch to a different branch or commit:
```
- [app-toolbar](/app-toolbar) - A horizontal toolbar containing items that can be used for label, navigation, search and actions.
```
I think the catalog could do something similar. wdyt?

**Comment by dstockwell** [comment]
https://github.com/webcomponents/beta/issues/345
