### ISSUE TITLE
Preview: element continues to fail preview process

### ISSUE THREAD

**Issue by ebidel** [webcomponents/beta#453]
[Origin page](https://beta.webcomponents.org/preview)

There's no way to get back to the previous page once an element  fails to preview. There should be a "Re-try" button or some.

![screen shot 2016-10-11 at 11 48 07 am](https://cloud.githubusercontent.com/assets/238208/19283909/9f152b78-8fa8-11e6-843e-44578cd9cd80.png)

**Comment by ebidel** [comment]
I should note that I updated the license in bower.json to `"license": "Apache-2.0",` and this still does not work after resubmitting. Is there a caching layer?

**Comment by dstockwell** [comment]
Cached by serviceworker :(
