### ISSUE TITLE
Logo gets cut off on smaller screens

### ISSUE THREAD

**Issue by ebidel** [webcomponents/beta#454]
[Origin page](https://beta.webcomponents.org/publish)

Reduced height:

![screen shot 2016-10-11 at 1 18 00 pm](https://cloud.githubusercontent.com/assets/238208/19287097/3a742464-8fb5-11e6-8b54-2a46ea2c2f18.png)

**Comment by dstockwell** [comment]
https://github.com/webcomponents/beta/issues/435
