### ISSUE TITLE
Search results: Be able to access all collections

### ISSUE THREAD

**Issue by samuelli** [webcomponents/beta#472]
eg. try browse all collections

**Comment by Nevraeka** [comment]
Many components are not listed that can be found on ce.io although the search is not very good there. Do we have a ticket for that or is it related to this? 

### results for `iron-lazy-pages`
[Search Results for component](https://drive.google.com/file/d/0BwCS6Yi3TwvvS1RpT3hmdjdHLTA/view)

### results for `tim`
[Search Results for author](https://drive.google.com/file/d/0BwCS6Yi3TwvvYTNDOVdjN3MwYjQ/view?usp=sharing)

On Ce.io...

* searching for `iron-lazy-pages` on ce.io yields no direct result
* searching with partial author name 'tim' shows it [high up in the results](https://customelements.io/search/tim)

**Comment by andymutton** [comment]
Any missing elements can be added at https://beta.webcomponents.org/publish. ce.io actively indexes elements with the "web-components" keyword in bower.json or package.json, beta.webcomponents requires elements to be submitted through the website.

I'm closing this issue as it is related to the ability to view all collections, which is now fixed.

**Comment by samuelli** [comment]
@Nevraeka: Yep, the source is fundamentally different. ce.io sourced everything with the 'web-components' keywords. In some cases, a lot of the listings on ce.io were highly questionable, ie. they weren't really web components that you can use.

The idea here is that with the new site we have a clean slate. I think it's important to set a relatively high bar for components, so we have a good set of quality elements. If we took all the ce.io components, I think we'd add a lot of noise. This way, we have a limited set of elements but the level of quality is much higher right now. Hopefully we can maintain that!

**Comment by Nevraeka** [comment]
Thanks for the clarification @andymutton & @samuelli . I like the 'opt in' approach much better. Authors are more invested that way. Down the road a cli tool (additional feature to one we have or a new one) for this might be a good development wrapper to further enable component authors to add this functionality to their existing processes (assuming an npm/yarn ecosystem)
