### ISSUE TITLE
Polymer/polymer is a dependency, but it isn't an element

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/beta#473]
[Origin page](https://beta.webcomponents.org/element/Polymer/polymer)

**Comment by samuelli** [comment]
This is a tricky one. I think we still want to show that it is a dependency. eg. it's important if jquery is a dependency even though its not an element

**Comment by abdonrd** [comment]
Sure! There is an option to not show as a link? For example, in the [paper-toggle-button](https://beta.webcomponents.org/element/PolymerElements/paper-toggle-button) show:

<img width="300" alt="screen shot 2016-10-13 at 00 43 16" src="https://cloud.githubusercontent.com/assets/1007051/19330348/3171f3a8-90de-11e6-8678-27f07101d27c.png">

**Comment by samuelli** [comment]
Hmm yeah, we'll need to compute whether or not we have it in our registry, which is tricky.

**Comment by dstockwell** [comment]
We can match it up with the data from `/api/dependencies`

**Comment by samuelli** [comment]
The whole dependencies section needs to be reworked tbh. Going to close this particular issue - I think once we migrate to NPM/Yarn this might be easier to solve. eg. we can point to the NPM listing if we don't have it.

**Comment by abdonrd** [comment]
ETA to NPM/Yarn migration?

**Comment by samuelli** [comment]
@abdonrd wish I knew - I have some ideas of how we might get there sooner, but too many variables to make blind promises!

**Comment by abdonrd** [comment]
@samuelli ok, thanks! 🙂
