### ISSUE TITLE
[content] Extract information from Resources Page

### ISSUE THREAD

**Issue by Nevraeka** [webcomponents/beta#506]
This was slated for redesign by myself & @treshugart but we never officially documented or worked on it in the old repo. We based this decision on outdated/incorrect informational content & very poor layout structure for the data we had. We should (in)validate any resources on that page that are still viable ad include them in this application somewhere TBD

**Comment by samuelli** [comment]
@tjsavage is going to take a look at this.

**Comment by samuelli** [comment]
Ref #629

**Comment by samuelli** [comment]
This should all be ported across now.
