### ISSUE TITLE
template is="dom-bind" doesn't work in inline demo

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/beta#510]
[Origin page](https://beta.webcomponents.org/element/abdonrd/device-orientation)

If I press the export to JSFiddle button, in the JSFiddle website works.

<img width="91" alt="screen shot 2016-10-13 at 18 43 49" src="https://cloud.githubusercontent.com/assets/1007051/19358307/b32caf4a-9175-11e6-8e80-8cff4b78c1d4.png">

I'm trying in a mobile phone to check the orientation.

**Comment by dstockwell** [comment]
The `<template>` element is being expanded inside `<head>`

If you add `<body>` (or any other non head element) before `<template>` it should work.

There's still a bug here, which is that export to JSFiddle should not wrap everything in `<body>`.

**Comment by dstockwell** [comment]
If you click on (HTML) on jsfiddle and change `BODY TAG` to `<html>` it will behave the same way.

**Comment by abdonrd** [comment]
@dstockwell thanks! Fixed at [webcomponents.org: abdonrd/device-orientation](https://beta.webcomponents.org/element/abdonrd/device-orientation)!
