### ISSUE TITLE
Deletion of published components

### ISSUE THREAD

**Issue by gronke** [webcomponents/beta#549]
I want to move a few recently published components to a different GitHub organization. @samuelli mentioned on the Polymer Summit the best way at the moment to do that is to file an issue here.

The 4 components I'd like to unpublish are:
- polymer-freegeoip-lookup
- polymer-openweathermap
- polymer-unit-prefix
- polymer-unit-convert

They're all coming back without the `polymer-` prefix by the way.

Thanks!

[Origin page](https://beta.webcomponents.org/element/gronke/polymer-freegeoip-lookup)

**Comment by samuelli** [comment]
@gronke: Done, the 4 of them have been unpublished.
