### ISSUE TITLE
Expand bower dependencies for a collection

### ISSUE THREAD

**Issue by samuelli** [webcomponents/beta#552]
Need the expanded version so inline demos for collections work. cc/ @andymutton

**Comment by samuelli** [comment]
@andymutton: is this fixed?

I re-published but it still shows only these dependencies. https://beta.webcomponents.org/api/docs/polymerelements/paper-input-elements

**Comment by andymutton** [comment]
Fixed? Yes. All elements re-analyzed? No. WIP.

**Comment by andymutton** [comment]
Re-analysis is done and all those dependencies are there now.
