### ISSUE TITLE
Code blocks overlay top nav when scrolling back.

### ISSUE THREAD

**Issue by ebidel** [webcomponents/beta#555]
[Origin page](https://beta.webcomponents.org/preview/samuelli/google-map/98703b21d4e2fa2fff95e4752bb0b8e4794ecf64)

<img width="1135" alt="screen shot 2016-10-21 at 8 25 54 am" src="https://cloud.githubusercontent.com/assets/238208/19603958/0a0e5230-9768-11e6-9045-a3e68b5c46e1.png">

**Comment by samuelli** [comment]
Fixed in #550, hasn't been pushed yet.
