### ISSUE TITLE
Missing iron-validatable-behavior.html

### ISSUE THREAD

**Issue by web-padawan** [webcomponents/beta#557]
Error appears when opening https://beta.webcomponents.org/element/web-padawan/brainy-table/demo/demo/index.html

```
GET https://user-content-dot-custom-elements.appspot.com/web-padawan/brainy-table/1.0.2/iron-a11y-announcer/iron-a11y-announcer.html 400 ()
index.html:364 GET https://user-content-dot-custom-elements.appspot.com/web-padawan/brainy-table/1.0.2/iron-validatable-behavior/iron-validatable-behavior.html 400 ()
polymer-micro.html:277 [paper-checkbox::_flattenBehaviorsList]: behavior is null, check for missing or 404 import
polymer-micro.html:277 [iron-input::_flattenBehaviorsList]: behavior is null, check for missing or 404 import
iron-input.html:121 Uncaught TypeError: Cannot read property 'requestAvailability' of undefined(…)
polymer.html:2017 Uncaught TypeError: Cannot set property 'invalid' of undefined(…)
```

**Comment by samuelli** [comment]
@andymutton: can you take a look? Most of the dependencies are there, but there's just a couple that seem to be missing. When I did bower install, they're all there in `bower list`.

**Comment by andymutton** [comment]
Output from analysis indicates that there are some missing dependencies in the bower.json causing hydrolysis to fail in part.

Also, this...
=========
bower/findDependencies/info/fail
bower/findDependencies/info failure info Error: No cached version for git://github.com/polymerelements/iron-validatable-behavior.git#^1.0.5
bower/findDependencies/info/fail
bower/findDependencies/info failure info Error: No cached version for git://github.com/polymerelements/iron-a11y-announcer.git#^1.0.4

I'll fork and see if fixing the missing deps fixes the problem.


Full console output below.
=====================================================
main/processTasks Debug mode - logging catalog responses to console.
main/processTasks/listen/success
analysis/processNextTask {"owner":"web-padawan","repo":"brainy-table","version":"1.1.1"}
bower/prune
bower/prune/success
bower/install web-padawan/brainy-table#1.1.1
bower/install/success web-padawan/brainy-table#1.1.1
hydrolysis/analyze [ '/Users/andymutton/dev/customelementsv2/analysis/bower_components/brainy-table/brainy-table.html' ]
bower/findDependencies web-padawan/brainy-table#1.1.1
ERROR finding /Users/andymutton/dev/customelementsv2/analysis/bower_components/paper-ripple/paper-ripple.html
hydrolysis/analyze/fail /Users/andymutton/dev/customelementsv2/analysis/bower_components/brainy-table/brainy-table.html
hydrolysis/analyze/success [ '/Users/andymutton/dev/customelementsv2/analysis/bower_components/brainy-table/brainy-table.html' ]
main/unhandledRejection/fail { Error: ENOENT: no such file or directory, open '/Users/andymutton/dev/customelementsv2/analysis/bower_components/paper-ripple/paper-ripple.html'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/andymutton/dev/customelementsv2/analysis/bower_components/paper-ripple/paper-ripple.html' }
main/unhandledRejection Error: ENOENT: no such file or directory, open '/Users/andymutton/dev/customelementsv2/analysis/bower_components/paper-ripple/paper-ripple.html'
bower/findDependencies/info/fail
bower/findDependencies/info failure info Error: No cached version for git://github.com/polymerelements/iron-validatable-behavior.git#^1.0.5
bower/findDependencies/info/fail
bower/findDependencies/info failure info Error: No cached version for git://github.com/polymerelements/iron-a11y-announcer.git#^1.0.4
catalog/postResponse
catalog/postResponse/debug attributes  {"owner":"web-padawan","repo":"brainy-table","version":"1.1.1"}
catalog/postResponse/debug data  {
	"elementsByTagName": {},
	"behaviorsByName": {},
	"bowerDependencies": [
		{
			"name": "brainy-table",
			"version": "1.1.1",
			"owner": "web-padawan",
			"repo": "brainy-table"
		},
		{
			"name": "polymer",
			"version": "v1.7.0",
			"owner": "Polymer",
			"repo": "polymer"
		},
		{
			"name": "iron-resizable-behavior",
			"version": "v1.0.5",
			"owner": "PolymerElements",
			"repo": "iron-resizable-behavior"
		},
		{
			"name": "paper-input",
			"version": "v1.1.20",
			"owner": "PolymerElements",
			"repo": "paper-input"
		},
		{
			"name": "iron-autogrow-textarea",
			"version": "v1.0.14",
			"owner": "PolymerElements",
			"repo": "iron-autogrow-textarea"
		},
		{
			"name": "iron-behaviors",
			"version": "v1.0.17",
			"owner": "PolymerElements",
			"repo": "iron-behaviors"
		},
		{
			"name": "iron-form-element-behavior",
			"version": "v1.0.6",
			"owner": "PolymerElements",
			"repo": "iron-form-element-behavior"
		},
		{
			"name": "iron-input",
			"version": "1.0.10",
			"owner": "PolymerElements",
			"repo": "iron-input"
		},
		{
			"name": "paper-styles",
			"version": "v1.1.5",
			"owner": "PolymerElements",
			"repo": "paper-styles"
		},
		{
			"name": "font-roboto",
			"version": "v1.0.1",
			"owner": "PolymerElements",
			"repo": "font-roboto"
		},
		{
			"name": "iron-a11y-keys-behavior",
			"version": "v1.1.9",
			"owner": "PolymerElements",
			"repo": "iron-a11y-keys-behavior"
		},
		{
			"name": "iron-icon",
			"version": "v1.0.12",
			"owner": "PolymerElements",
			"repo": "iron-icon"
		},
		{
			"name": "iron-meta",
			"version": "v1.1.2",
			"owner": "polymerelements",
			"repo": "iron-meta"
		},
		{
			"name": "iron-iconset-svg",
			"version": "v1.1.0",
			"owner": "PolymerElements",
			"repo": "iron-iconset-svg"
		},
		{
			"name": "webcomponentsjs",
			"version": "v0.7.22",
			"owner": "Polymer",
			"repo": "webcomponentsjs"
		},
		{
			"name": "iron-demo-helpers",
			"version": "v1.2.5",
			"owner": "PolymerElements",
			"repo": "iron-demo-helpers"
		},
		{
			"name": "paper-icon-button",
			"version": "v1.1.3",
			"owner": "PolymerElements",
			"repo": "paper-icon-button"
		},
		{
			"name": "marked-element",
			"version": "v1.2.0",
			"owner": "polymerelements",
			"repo": "marked-element"
		},
		{
			"name": "marked",
			"version": "v0.3.6",
			"owner": "chjj",
			"repo": "marked"
		},
		{
			"name": "prism-element",
			"version": "v1.1.1",
			"owner": "PolymerElements",
			"repo": "prism-element"
		},
		{
			"name": "prism",
			"version": "1.5.1",
			"owner": "LeaVerou",
			"repo": "prism"
		},
		{
			"name": "iron-location",
			"version": "v0.8.9",
			"owner": "PolymerElements",
			"repo": "iron-location"
		},
		{
			"name": "paper-checkbox",
			"version": "v1.4.1",
			"owner": "PolymerElements",
			"repo": "paper-checkbox"
		},
		{
			"name": "iron-checked-element-behavior",
			"version": "v1.0.5",
			"owner": "PolymerElements",
			"repo": "iron-checked-element-behavior"
		},
		{
			"name": "paper-behaviors",
			"version": "v1.0.12",
			"owner": "PolymerElements",
			"repo": "paper-behaviors"
		},
		{
			"name": "paper-ripple",
			"version": "v1.0.10",
			"owner": "PolymerElements",
			"repo": "paper-ripple"
		},
		{
			"name": "paper-button",
			"version": "v1.0.14",
			"owner": "PolymerElements",
			"repo": "paper-button"
		},
		{
			"name": "paper-material",
			"version": "v1.0.6",
			"owner": "PolymerElements",
			"repo": "paper-material"
		},
		{
			"name": "web-component-tester",
			"version": "4.3.1",
			"owner": "Polymer",
			"repo": "web-component-tester"
		},
		{
			"name": "accessibility-developer-tools",
			"version": "v2.11.0",
			"owner": "GoogleChrome",
			"repo": "accessibility-developer-tools"
		},
		{
			"name": "async",
			"version": "v1.5.2",
			"owner": "caolan",
			"repo": "async"
		},
		{
			"name": "chai",
			"version": "3.5.0",
			"owner": "chaijs",
			"repo": "chai"
		},
		{
			"name": "lodash",
			"version": "3.10.1",
			"owner": "lodash",
			"repo": "lodash"
		},
		{
			"name": "mocha",
			"version": "v2.5.3",
			"owner": "mochajs",
			"repo": "mocha"
		},
		{
			"name": "sinon-chai",
			"version": "2.8.0",
			"owner": "domenic",
			"repo": "sinon-chai"
		},
		{
			"name": "sinonjs",
			"version": "v1.17.1",
			"owner": "blittle",
			"repo": "sinon.js"
		},
		{
			"name": "stacky",
			"version": "v1.3.2",
			"owner": "PolymerLabs",
			"repo": "stacky"
		},
		{
			"name": "test-fixture",
			"version": "v1.1.1",
			"owner": "PolymerElements",
			"repo": "test-fixture"
		},
		{
			"name": "iron-test-helpers",
			"version": "v1.2.5",
			"owner": "PolymerElements",
			"repo": "iron-test-helpers"
		},
		{
			"name": "iron-flex-layout",
			"version": "v1.3.1",
			"owner": "PolymerElements",
			"repo": "iron-flex-layout"
		},
		{
			"name": "iron-component-page",
			"version": "v1.1.7",
			"owner": "PolymerElements",
			"repo": "iron-component-page"
		},
		{
			"name": "hydrolysis",
			"version": "v1.24.1",
			"owner": "Polymer",
			"repo": "hydrolysis"
		},
		{
			"name": "iron-doc-viewer",
			"version": "v1.0.15",
			"owner": "PolymerElements",
			"repo": "iron-doc-viewer"
		},
		{
			"name": "iron-selector",
			"version": "v1.5.2",
			"owner": "PolymerElements",
			"repo": "iron-selector"
		},
		{
			"name": "paper-header-panel",
			"version": "v1.1.7",
			"owner": "PolymerElements",
			"repo": "paper-header-panel"
		},
		{
			"name": "paper-toolbar",
			"version": "v1.1.7",
			"owner": "PolymerElements",
			"repo": "paper-toolbar"
		},
		{
			"name": "iron-ajax",
			"version": "v1.4.3",
			"owner": "PolymerElements",
			"repo": "iron-ajax"
		},
		{
			"name": "promise-polyfill",
			"version": "v1.0.1",
			"owner": "polymerlabs",
			"repo": "promise-polyfill"
		},
		{
			"name": "iron-icons",
			"version": "v1.1.3",
			"owner": "PolymerElements",
			"repo": "iron-icons"
		},
		{
			"name": "paper-tabs",
			"version": "v1.7.0",
			"owner": "PolymerElements",
			"repo": "paper-tabs"
		},
		{
			"name": "iron-menu-behavior",
			"version": "v1.2.0",
			"owner": "PolymerElements",
			"repo": "iron-menu-behavior"
		},
		{
			"name": "iron-pages",
			"version": "v1.0.8",
			"owner": "PolymerElements",
			"repo": "iron-pages"
		},
		{
			"name": "vaadin-combo-box",
			"version": "v1.1.5",
			"owner": "vaadin",
			"repo": "vaadin-combo-box"
		},
		{
			"name": "iron-form",
			"version": "v1.1.4",
			"owner": "polymerelements",
			"repo": "iron-form"
		},
		{
			"name": "iron-list",
			"version": "v1.3.11",
			"owner": "polymerelements",
			"repo": "iron-list"
		},
		{
			"name": "iron-scroll-target-behavior",
			"version": "v1.1.0",
			"owner": "PolymerElements",
			"repo": "iron-scroll-target-behavior"
		}
	]
}
analysis/processNextTask/success {"owner":"web-padawan","repo":"brainy-table","version":"1.1.1"}
main/processTasks/success

**Comment by andymutton** [comment]
I've figured it out. For some reason bower is case-sensitive when looking through its cache in offline mode to return package info. Patch incoming...
