### ISSUE TITLE
Only list 4 collections

### ISSUE THREAD

**Issue by abdonrd** [webcomponents/beta#566]
[Origin page](https://beta.webcomponents.org/author/PolymerElements)

Only list 4 collections, instead of 13:

<img width="1184" alt="screen shot 2016-10-24 at 23 36 30" src="https://cloud.githubusercontent.com/assets/1007051/19664875/bca6490c-9a42-11e6-9039-5702dc15fed3.png">

**Comment by dstockwell** [comment]
https://github.com/webcomponents/beta/issues/472
