### ISSUE TITLE
Missing dependencies on demo

### ISSUE THREAD

**Issue by LostInBrittany** [webcomponents/beta#577]
Hi!

In one of my components, [granite-qrcode-generator](), the demo is broken on beta.webcomponents.org because it isn't able to get one of my dependencies, *qr.js*

The problem seems to come from the `user-content-dot-custom-elements.appspot.com` redirection.

The call for `qr.js` is:

```
https://user-content-dot-custom-elements.appspot.com/LostInBrittany/granite-qrcode-generator/1.0.2/qrjs/qr.js
```

And it should redirect to:

```
https://cdn.rawgit.com/lifthrasiir/qr.js/v0.0.20110119/qr.js
```

But instead it redirects to:

```
https://cdn.rawgit.com/lifthrasiir/lifthrasiir//v0.0.20110119/qr.js
```

And then it gets a (very logical) 404.

Any idea of why? Is there something I should do on my end?

**Comment by dstockwell** [comment]
That dependency is showing up as
```{json
{"owner": "lifthrasiir", "repo": "lifthrasiir/", "version": "v0.0.20110119", "name": "qrjs"}
```

@andymutton
