### ISSUE TITLE
Inline demo should be aware of resizing rendered element

### ISSUE THREAD

**Issue by web-padawan** [webcomponents/beta#597]
Please take a look at the [brainy-table](https://beta.webcomponents.org/element/web-padawan/brainy-table) element. 
It loads data asynchronously, and now (on first page load, or after cleaning cache) demo area doesn't get expanded after finishing load and drawing table.
However, resizing browser window forces demo to recalculate its height. So my suggestion is that `notifyResize` should be called somewhere.
Further loads are seems to be cached and so table renders faster, without having this issue.

**Comment by samuelli** [comment]
Hmm, we listen for a 'resize' event, so I'm not sure why that doesn't get picked up. A workaround is to set an explicit height in your container div.

We may need to listen for more resize events, but I'd have to test if this is something we can fix.

**Comment by samuelli** [comment]
This doesn't seem to be an issue anymore.

Let me know if there's any other issues you're seeing!
