### ISSUE TITLE
Decide: should we move "Getting started w/ Web Components" section to the top of the homepage?

### ISSUE THREAD

**Issue by tjsavage** [webcomponents/beta#626]
On one hand, it's nice to see the latest components right away.

On the other, for people new to web components it's bad to bury the getting started material below-the-fold.

Feedback appreciated!

**Comment by TimvdLippe** [comment]
Maybe show the message initially, but the user can click the message away with a `X` in the top right corner?

**Comment by samuelli** [comment]
Particularly with the move towards webcomponents.org:
 * those familiar with wc.org will want to see what's new (ie. elements)
 * those new to wc.org are trying to determine what web components are. I would argue that showing real, live components is a powerful introduction to web components. "These awesome elements like this really cool ____, I want to find out more about web components" and then progressing to article based content.

We can also show a first time user experience when we move out of beta.

Closing this for now, feel free to add your thoughts though.
