### ISSUE TITLE
Template seems broken

### ISSUE THREAD

**Issue by samuelli** [webcomponents/beta#649]
[Origin page](https://beta.webcomponents.org/element/diddledan/proportional-height-box)

**Comment by samuelli** [comment]
Seems to be a common problem. Maybe don't add if next-code-block isn't used? Maybe a comment to explain what it does?

**Comment by dstockwell** [comment]
I don't think this is from the creator. It ouputs the second code block with `html`. Maybe copy pasta from the `/publish` page which doesn't (but should?).

Perhaps we show the demo creator on the `/publish` page, and add some text to describe what `<next-code-block>` does.

**Comment by samuelli** [comment]
Hopefully fixed in #670
