### ISSUE TITLE
Last updated seems wrong

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/beta#656]
[Origin page](https://beta.webcomponents.org/element/acordeonl/ajax-manager)

This repo's first commit was added 14 hours ago, but the site says:

![screenshot 2016-11-14 at 14 24 52](https://cloud.githubusercontent.com/assets/539597/20285346/32e1b0e6-aa76-11e6-993e-d8e59641ecfc.png)

**Comment by samuelli** [comment]
Is this worth fixing? I would probably need to send `created_at` back from metadata, then use that as a floor. Seems like its not worth it? @dstockwell 
This repo has already been deleted.
