### ISSUE TITLE
Demos should use demo-snippet elements 

### ISSUE THREAD

**Issue by nerdkid93** [webcomponents/beta#659]
Demos currently only show the demoed elements. They should instead use demo-snippet to show code along with the elements.

**Comment by dstockwell** [comment]
Do you have an example?

**Comment by samuelli** [comment]
@nerdkid93: is there a sample page? For the full-screen demos, a lot of the demos already use demo-snippet, but its really up to the author.

**Comment by samuelli** [comment]
@nerdkid93: Closing this since I'm not sure if this is something we can fix on our side.

Let me know if there are any updates.
