### ISSUE TITLE
Dual license not accepted.

### ISSUE THREAD

**Issue by jarrodek** [webcomponents/beta#677]
[Origin page](https://beta.webcomponents.org/element/advanced-rest-client/paper-masked-input#feedback)

I have a following error when trying to publish an element: 
> Could not detect an OSI approved license on GitHub or in stage/bower.json

The licence entry in bower file:
```
"license":"Apache-2.0 OR CC-BY-4.0"
```
Both are open. I can't find creative commons licences in the OSI list but it is still an open license.

**Comment by samuelli** [comment]
Hi @jarrodek:

Based on the bower.json spec, we only support a single SPDX identifier in the license field. From looking at the CC license, there is a list of attribution requirements which could make it pretty complex for the developer to handle. Another summary of it here: https://creativecommons.org/licenses/by/4.0/

Thoughts?

**Comment by samuelli** [comment]
Closing for now.
@jarrodek: let me know if there's any changes.
