### ISSUE TITLE
Inline demo templates not binding

### ISSUE THREAD

**Issue by sbeleidy** [webcomponents/beta#701]
I've been having issues with the inline demo and data-binding. I can't seem to get it to work.

What I've tried so far:
1. using `<template>` in the commented code section
1. using `<template is="dom-bind">` in the commented code section
1. using a `<template>` inside the next code block

Live previews that are failing to bind but seem to work fine in the sidebar demos:
* [Presence-fire](https://beta.webcomponents.org/preview/convoo/presence-fire/435059f777769dd7d1acf623770f190f32bef892) - [code](https://github.com/convoo/presence-fire/tree/master)
* [json-box](https://beta.webcomponents.org/preview/sbeleidy/json-box/9d73814548e97e52161dae186fa50315528d2c6f) - [code](https://github.com/sbeleidy/json-box)

**Comment by samuelli** [comment]
So after a bit of digging, the issue is that `<template is="dom-bind">` only works in `body`.

Workarounds include using `<dom-bind>` instead, inserting `<body>` before `<template is="dom-bind">`, or inserting another element which can't be used in `<head>`, such as a `<div>`.

I'll try think of ways to clarify this in the inline-demo creator.

Sorry this wasn't more obvious! Also thanks for reporting this.

**Comment by sbeleidy** [comment]
Thanks for getting back to me!

I tried your 3 suggestions and they didn't work for me. Could you please take a look and let me know what I did wrong?

* switch to `<dom-bind>` [demo](https://beta.webcomponents.org/preview/convoo/presence-fire/5b87f633e4e7bebe0ada0781730107086497166c) - [code](https://github.com/convoo/presence-fire/commit/5b87f633e4e7bebe0ada0781730107086497166c)
* prepend with `<body>` [demo](https://beta.webcomponents.org/preview/convoo/presence-fire/61ff25e4c36a7ecae51f2ab2cf659a4b0a7ea3aa) - [code](https://github.com/convoo/presence-fire/commit/61ff25e4c36a7ecae51f2ab2cf659a4b0a7ea3aa)
* prepend with `<div>` [demo](https://beta.webcomponents.org/preview/convoo/presence-fire/b025baa0b4fc048ccc2a633ffd4d17b72490ab72) - [code](https://github.com/convoo/presence-fire/commit/b025baa0b4fc048ccc2a633ffd4d17b72490ab72)

For when you update the demo creator and code snippets: I'd recommend settling on one way of doing things and then adding that in the inline-demo-creator instead of giving folks multiple options. That should be less confusing and hopefully more consistent. In the future in case anything changes, you'd have everyone theoretically following the same demo structure.

I hope this helps.

**Comment by samuelli** [comment]
Thanks for providing the code! Sorry I wasn't clear, here's what the source should be. You still need the outside `template` tag.

```
<custom-element-demo>
  <template>
    <link rel="import" href="../polymerfire/firebase-app.html">
    <link rel="import" href="../login-fire/social-login-fire.html">
    <link rel="import" href="../paper-button/paper-button.html">
    <link rel="import" href="../paper-input/paper-input.html">
    <link rel="import" href="../paper-toggle-button/paper-toggle-button.html">
    <link rel="import" href="presence-fire.html">
    <dom-bind>
      <next-code-block></next-code-block>
    </dom-bind>
  </template>
</custom-element-demo>
```

Given that `dom-bind` is a Polymer construct, its a little hard to explain why this is happening. I'll do my best!

**Comment by sbeleidy** [comment]
Still not working for me 😕 

* With parent `<template is="dom-bind">` [demo](https://beta.webcomponents.org/preview/convoo/presence-fire/6572cfec84e11c6b72cece381b4b00bee98fcf5a) - [code](https://github.com/convoo/presence-fire/commit/6572cfec84e11c6b72cece381b4b00bee98fcf5a) (I know you didn't say to do this, I accidentally forgot to remove the `is="dom-bind"` but figured it might be helpful for you to see anyway)
* With parent `<template>` [demo](https://beta.webcomponents.org/preview/convoo/presence-fire/eea00c1e994512564b93f8264f06385ec71dd8d9) - [code](https://github.com/convoo/presence-fire/commit/eea00c1e994512564b93f8264f06385ec71dd8d9)

Sorry to keep going back and forth.

**Comment by sbeleidy** [comment]
Thanks @samuelli!

Based on your recommendation, this was the code block structure that got it to work:

```html
<custom-element-demo>
    <template>
        <link rel="import" href="../other-element/other-element.html">
        <link rel="import" href="my-element.html">
        <div>
            <template is="dom-bind">
                <next-code-block></next-code-block>
            </template>
            <script>
// Scripts
            </script>
            <style>
// Styles
            </style>
          </div>
      </template>
</custom-element-demo>    
```
