### ISSUE TITLE
After interaction, component states "undefined"

### ISSUE THREAD

**Issue by sbeleidy** [webcomponents/beta#710]
After clicking on one of the buttons in the [demo](https://beta.webcomponents.org/preview/convoo/login-fire/b072f3805f20c0ff2180492d1635365b4307bf7e) for [login-fire](https://github.com/convoo/login-fire/tree/38_fix_demo) the component becomes 'undefined' with no errors displayed in the console.

I had initially assumed the issue was due to data binding but after applying the solution from #701 it's still happening. Previously it wouldn't open the sign-in popups, now it opens them but the element still becomes 'undefined'. You can reproduce by clicking "Sign in with Google" button for example (no need to actually sign in after that).

![screen shot 2016-12-12 at 9 24 05 pm](https://cloud.githubusercontent.com/assets/1388511/21127589/5f87beb4-c0b1-11e6-9ff4-c70937813931.png)

**Comment by samuelli** [comment]
Fixed! It doesn't say `undefined` anymore.
