### ISSUE TITLE
Unexpected search ordering

### ISSUE THREAD

**Issue by rictic** [webcomponents/beta#713]
For this search: https://beta.webcomponents.org/search/paper-button

### Expected

`<paper-button>` to be at the top, or at least the top results to be some combination of the most popular and closest textual match to the tag name

### Actual

`<paper-button>`, which has the most github stars and is the closest match to the search is the fifth search result.

Top ten search results:

1. material-toggle-button
2. paper-buttons-group
3. paper-button-group
4. paper-icon-button
5. paper-button
6. paper-confirm-button
7. paper-toggle-button
8. paper-more-button
9. paper-radio-button
10. paper-menu-button

**Comment by samuelli** [comment]
Hmm, this is tricky to rectify. I think in our attempts to make sure better, we've actually degraded quality in some cases. The prefix matching and description mean that `button` can get matched more often and produces higher rankings.

Two solutions come to mind:
 * Implement weighting - not supported by GAE, but we could implement our own weighting system which works by adding a field multiple times to the search document based on its weight.
 * Implement a second query and coalesce results - searching for `repo: paper-button` produces more expected results, so we could merge these with the existing results. This would double the number of search queries & hence performance and I imagine the coalescing will be difficult with cursors etc.

@dstockwell: thoughts? I'm leaning towards the weighting solution to fake field weighting.

**Comment by samuelli** [comment]
Thanks for filing @rictic!

Latest set of results for the same query:
![image](https://cloud.githubusercontent.com/assets/787668/21300972/00e6716a-c5fd-11e6-9cdb-39f0c4f5dfef.png)

**Comment by rictic** [comment]
Awesome! I tried a handful of other searches and the results all seemed great. Thanks!
