### ISSUE TITLE
API access intention

### ISSUE THREAD

**Issue by deedubbu** [webcomponents/beta#718]
I'm currently developing an enhancement to a development environment and would like to include the ability for a user to browse the published web components and view documentation from within the environment. Essentially I'd like to provide the user in context access to information provided by the beta webcomponents [API](https://github.com/webcomponents/beta/blob/master/API.md) so that as they are developing they can find new web components and read the details about the components.

In the application the user would be able to search the web components database and then select a repo to access the associated documentation. I've been playing with the API a bit and have been pleased with the performance and available information. I'm currently planning on using the following API:

`GET /api/search/:query`
`GET /api/docs/:owner/:repo`

I'm opening this issue to acknowledge my usage of the API as requested in the API documentation. Please advise me of any restrictions or limitations.

**Comment by samuelli** [comment]
That sounds awesome!

Let us know if there's any changes we need to make.

I don't expect the search api to change, but the docs API may change. @andymutton: any idea if this will change once we switch to Analyzer?

**Comment by samuelli** [comment]
I'm going to close this, feel free to ping on the Gitter or here. We'll try make sure we update here when we do expect a change in the API.
