### ISSUE TITLE
Element docs and demos not registered due to external script reference

### ISSUE THREAD

**Issue by justincy** [webcomponents/beta#726]
I recently published a [collection of 10 elements](https://beta.webcomponents.org/collection/fs-webcomponents/fs-elements). The elements were all published but docs and demos were not registered for elements in the "Repository contents" panel in the right side bar. Docs for behaviors registered (e.g. [fs-behavior](https://beta.webcomponents.org/element/fs-webcomponents/fs-behavior)) but not for elements (e.g. [fs-signin](https://beta.webcomponents.org/element/fs-webcomponents/fs-signin)).

I tracked the issue down to [fs-client](https://beta.webcomponents.org/element/fs-webcomponents/fs-client) (which all elements depend on) [referencing an external script](https://github.com/fs-webcomponents/fs-client/blob/3f819c005230f09677d7d194657204a520aa1caa/fs-client.html#L2) via a CDN. 

The src in master uses the protocol relative URL. Adding `https://` removes the error from the CLI output but hydrolysis still fails. Adding a debug statement for the error reveals: 

```
Error: no resolver found for https://unpkg.com/fs-js-lite@2.0.0/dist/FamilySearch.min.js
    at FileLoader.request (/home/ubuntu/workspace/beta/analysis/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Analyzer._processScript (/home/ubuntu/workspace/beta/analysis/node_modules/hydrolysis/lib/analyzer.js:378:36)
    at /home/ubuntu/workspace/beta/analysis/node_modules/hydrolysis/lib/analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (/home/ubuntu/workspace/beta/analysis/node_modules/hydrolysis/lib/analyzer.js:300:21)
    at Analyzer._parseHTML (/home/ubuntu/workspace/beta/analysis/node_modules/hydrolysis/lib/analyzer.js:161:39)
    at null._onTimeout (/home/ubuntu/workspace/beta/analysis/node_modules/hydrolysis/lib/analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
```

I'll try installing the script via bower. Any other tips?

**Comment by justincy** [comment]
Installing via bower doesn't look like it's going to work. I refuse to commit packaged assets to GitHub and use [unpkg](https://unpkg.com/#/) to avoid it. unpkg currently supports bower but will remove that feature next month.

Is there a way to tell Hydrolysis to ignore external URLs?

**Comment by justincy** [comment]
Removing the `filter` option from the [analyzer options](https://github.com/webcomponents/beta/blob/4a20de61fd1a329e9a4d0011db660fc7b5e1b4b0/analysis/src/hydrolysis.js#L47) fixes the issue because the default filter is to ignore all files not located in the same directory as the file being analyzed. Is there a reason the filter is set to allow all files?

**Comment by samuelli** [comment]
@andymutton: can we use the default `filter` as @justincy suggested?

**Comment by samuelli** [comment]
@andymutton: This is the `defaultFilter` [implementation in polymer-analyzer](https://github.com/Polymer/polymer-analyzer/blob/hydrolysis-1.x/src/analyzer.ts#L728).

We should probably just implement our own filter here.

**Comment by justincy** [comment]
Thanks! It looks like the PR will solve my issue.

It doesn't appear the fix has been deployed. Is that correct? I realize that builds are cached (even previews; smart move!) so I pushed an empty commit but nothing changed. Once the fix is live, is there a way to force a rebuild? I'm willing to do more empty commits but I'd prefer not to.

**Comment by samuelli** [comment]
Yep, it hasn't been deployed yet. We can trigger the rebuild.

@andymutton: can you deploy and trigger?

**Comment by andymutton** [comment]
Deployed to staging and running there. Will then do prod.

**Comment by andymutton** [comment]
https://custom-elements-staging.appspot.com/element/fs-webcomponents/fs-client/fs-client seems legit. Other elements are unaffected. Will push to prod.

**Comment by andymutton** [comment]
Pushed successfully and reanalyzed fs-client. <fs-client> is now in the repo contents.
