### ISSUE TITLE
"Take me back" has no effect when google-analytics.js blocked

### ISSUE THREAD

**Issue by tony19** [webcomponents/beta#728]
My ad blocker blocks `google-analytics.js`, which somehow prevents the redirect toast's "Take me back" button from working. There is no log in the console when this occurs. DevTools shows that the only thing "ad-blocked" on this site is `google-analytics.js`. Manually adding an exception (or disabling the ad-blocker for this page) allows the link to return me to the classic Polymer Elements catalog.

The relevant [code](https://github.com/webcomponents/beta/blob/dc57a3b/client/src/catalog-app.html#L755-L760):
```javascript
      _optOut: function() {
        function navigate() {
          window.location.href = 'https://elements.polymer-project.org?redirect=';
        }
        /* global ga */
        if (window.ga) {
          ga('send', 'event', {
            eventCategory: 'Optout',
            eventAction: 'Toast',
            eventLabel: 'Polymer Elements redirect',
            transport: 'beacon',
            hitCallback: navigate,
          });
        } else {
          navigate();
        }
      },
```

I'm guessing that `window.ga` exists even when blocked, but since it's blocked, `hitCallback` is never invoked, so `navigate()` never gets called.

### Environment

 * macOS Sierra 10.12
 * Chrome 54
 * [AdBlock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom?hl=en-US) 3.8.1

**Comment by samuelli** [comment]
Thanks for filing - do you want to send a pull request to fix this issue?

**Comment by tony19** [comment]
@samuelli Ok. See #746
