### ISSUE TITLE
Rename `Featured` to `Fresh`?

### ISSUE THREAD

**Issue by dstockwell** [webcomponents/beta#741]
I think that's a better description of what we're showing.

**Comment by samuelli** [comment]
It so happens that our featured ones are fresh. I don't think fresh is completely accurate either - if someone files a GitHub issue, then it becomes 'fresh'. Also 'featured' gives us more room to move, if we wanted to change featured to only contain inline demos, we can do that. It currently already does not show the 3 'freshest' elements.
