### ISSUE TITLE
README.md not indexed

### ISSUE THREAD

**Issue by the-catalin** [webcomponents/beta#757]
I published two elements
https://beta.webcomponents.org/element/the-catalin/cat-text
https://beta.webcomponents.org/element/the-catalin/cat-image

they both have readme.md files as seen at
https://github.com/the-catalin/cat-text
https://github.com/the-catalin/cat-image

but they show as empty on the published page on webcomponents.org website.

Upon previewing the element using the preview tool ( https://beta.webcomponents.org/preview ) the readme file shows correctly.

Maybe I've used an illegal character, as I've seen other elements are showing fine, but which one?

Thanks!

**Comment by dstockwell** [comment]
In the 0.5.0 tagged versions of your elements there is no readme.md 

Eg. https://github.com/the-catalin/cat-text/tree/deebb70945ef9a52a8b02c3bee07d37e7bc874e3

If you tag a new release the readme should appear as it does in the preview.

**Comment by the-catalin** [comment]
You're right, thank you!

I'm not yet very aware of all details on github.
